NA-18848 - fixing ECR creation bug

diff --git a/.github/workflows/default_build.yaml b/.github/workflows/default_build.yaml
--- a/.github/workflows/default_build.yaml
+++ b/.github/workflows/default_build.yaml
@@ -73,17 +73,14 @@ jobs:
 
       - name: ECR repo setup 
         run: |
-          output=$(aws ecr describe-repositories --repository-names ${{ inputs.ECR_REPO }} 2>&1)
-          if [ $? -ne 0 ]; then
-            if echo ${output} | grep -q RepositoryNotFoundException; then
-              echo "Repository Not Found. Creating new ECR repo: ${{ inputs.ECR_REPO }}"
-              aws ecr create-repository --repository-name ${{ inputs.ECR_REPO }} >/dev/null 2>&1
-              sudo aws s3 cp --recursive s3://sxdev-devops/policies/ecr/ .
-              aws ecr set-repository-policy --repository-name ${{ inputs.ECR_REPO }} --policy-text file://ecr_policy.json  >/dev/null 2>&1
-              aws ecr put-lifecycle-policy --repository-name ${{ inputs.ECR_REPO }} --lifecycle-policy-text file://ecr_lifecycle_policy.json >/dev/null 2>&1
-            else
-              >&2 echo ${output}
-            fi
+          aws ecr describe-repositories --repository-names ${{ inputs.ECR_REPO }} 2>&1 > /dev/null
+          status=$?
+          if [[ ! "${status}" -eq 0 ]]; then
+            echo "Repository Not Found. Creating new ECR repo: ${{ inputs.ECR_REPO }}"
+            aws ecr create-repository --repository-name ${{ inputs.ECR_REPO }} >/dev/null 2>&1
+            aws s3 cp --recursive s3://sxdev-devops/policies/ecr/ .
+            aws ecr set-repository-policy --repository-name ${{ inputs.ECR_REPO }} --policy-text file://ecr_policy.json  >/dev/null 2>&1
+            aws ecr put-lifecycle-policy --repository-name ${{ inputs.ECR_REPO }} --lifecycle-policy-text file://ecr_lifecycle_policy.json >/dev/null 2>&1
           fi
 
       - name: Set up Docker Context for Buildx
