NA-20327 new autocopy wf changes

diff --git a/.github/workflows/default_deploy_k8s_prod_trading.yaml b/.github/workflows/default_deploy_k8s_prod_trading.yaml
--- a/.github/workflows/default_deploy_k8s_prod_trading.yaml
+++ b/.github/workflows/default_deploy_k8s_prod_trading.yaml
@@ -1,25 +1,29 @@
-name: "Deploy to dev k8s"
+name: "Deploy to production k8s"
 
 on:
   workflow_call:
 
     inputs:
-      SLACK_DEV_DEPLOY_CHANNEL_ID:
+      SLACK_PROD_DEPLOY_CHANNEL_ID:
         type: string
         required: true
-        description: '#gh-deploy-dev ID'
+        description: '#gh-deploy-prod ID'
       NAMESPACE:
         type: string
         required: true
         description: 'Namespace in the cluster'
       KUSTOMIZE_OVERLAY:
         type: string
-        required: true
+        required: true 
         description: 'Path to Kustomize overlay'
       KUSTOMIZE_ROOT:
         type: string
         required: true
-        description: 'Path to Kustomize base'
+        description: 'Path to Kustomize root'
+      IMAGE_TAG:
+        type: string
+        required: true
+        description: 'Image tag to deploy'
       CF_DISTRIBUTION_ID:
         type: string
         required: true
@@ -28,6 +32,10 @@ on:
         type: string
         required: true
         description: 'CloudFront invalidations paths'
+      SERVICE:
+        type: string
+        required: true
+        description: 'Service to deploy'
     secrets:
       slack-bot-token:
         required: true
@@ -43,19 +51,25 @@ on:
         required: true
 
 jobs:  
-  deploy_dev:
-    runs-on: small-runner
+  deploy_production:
+    runs-on: small-prod-runner
     outputs:
-      SLACK_MESSAGE_ID: ${{ steps.gh-deploy-dev.outputs.message_id }}
-      TAG: ${{ env.TAG }}
       GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
-      
+
     steps:
+      - name: Check image tag 
+        run: | 
+          if [[ ! ${{ inputs.IMAGE_TAG }} =~ ^[a-z]+[-] ]] ; then 
+            echo 'Invalid Image Tag'
+            echo 'must be in {BRANCH_NAME}-{SHA} format'
+            echo 'etc: master-2b7f922'
+            exit 1
+          fi
+    
       - name: Set environment variables
-        id: envs 
         run: |
-          TAG=${GITHUB_REF##*/}-`echo ${GITHUB_SHA} | cut -c1-7`
-          echo "TAG=${GITHUB_REF##*/}-`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
+          TAG=${{ inputs.IMAGE_TAG }}
+          echo "TAG=${{ inputs.IMAGE_TAG }}" >> $GITHUB_ENV 
           echo "GITHUB_ACTOR=${GITHUB_ACTOR}" >> $GITHUB_ENV
           echo "JOB_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
 
@@ -65,13 +79,13 @@ jobs:
           username: ${{ secrets.dockerhub-username }}
           password: ${{ secrets.dockerhub-token }}
 
-      - name: Notify Slack of Deploy
-        id: gh-deploy-dev
+      - name: Notify Slack of Production Deploy
+        id: gh-deploy-prod
         uses: voxmedia/github-action-slack-notify-build@v1
         with:
-          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
+          channel_id: ${{ inputs.SLACK_PROD_DEPLOY_CHANNEL_ID }}
           status: |
-            Deploying Image on DEV
+            Deploying Image on Production
 
             - Image Tag: ${{ env.TAG }}
             - Actor: ${{ env.GITHUB_ACTOR }}
@@ -81,22 +95,16 @@ jobs:
           SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}
 
       - name: Checkout
-        uses: actions/checkout@v3
-
-      - name: List Directory
-        run: |
-          cd .kube/main/base/
-          ls -la
+        uses: actions/checkout@v1
 
       # This step causes issues when used as a composite action
       # Therefore the Script is executed from the step directly
       # This could be the subject of the next upgrade
       - name: Inject image tag into files
-        working-directory: ./
         run: |
           sudo apt-get update -y
           sudo apt-get install gettext -y
-          FILES=(${{ inputs.KUSTOMIZE_ROOT }}/base/* ${{ inputs.KUSTOMIZE_ROOT }}/overlays/dev/*)
+          FILES=(${{ inputs.KUSTOMIZE_ROOT }}/base/* ${{ inputs.KUSTOMIZE_OVERLAY }}/*)
           for FILE in ${FILES[@]}; do
             if [[ -n ${PATTERN} ]] ; then
               envsubst "${PATTERN}" < $FILE > /tmp/envsubst || exit 1
@@ -106,13 +114,13 @@ jobs:
             mv /tmp/envsubst $FILE || exit 1
           done
         env:
-          PATTERN: $TAG 
+          PATTERN: $TAG
 
-      # Deploy the branch to the namespace defined in the resource YAMLs
       - name: Deploy
-        uses: SwipeStoxGmbH/reusable-workflows/actions/deploy@master
+        uses: SwipeStoxGmbH/reusable-workflows/actions/deploy-autocopy@master
         with:
           NAMESPACE: ${{ inputs.NAMESPACE }}
+          SERVICE: ${{ inputs.SERVICE }}
           KUSTOMIZE_OVERLAY: ${{ inputs.KUSTOMIZE_OVERLAY }}
 
       - name: Invalidate CloudFront
@@ -125,40 +133,36 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}
 
-      # - name: Create Git Tag 
-      #   uses: rickstaa/action-create-tag@v1
-      #   with:
-      #     tag: ${{ env.TAG }}
-      #     message: ${{ env.TAG }}
-
       - name: Notify Slack of Success
         if: success()
         uses: voxmedia/github-action-slack-notify-build@v1
         with:
-          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
-          message_id: ${{ steps.gh-deploy-dev.outputs.message_id }}
+          channel_id: ${{ inputs.SLACK_PROD_DEPLOY_CHANNEL_ID }}
+          message_id: ${{ steps.gh-deploy-prod.outputs.message_id }}
           status: |
-            Image Deployed on DEV
+            Image Deployed on Production
 
-            - Image Tag: ${{ env.TAG }}
+            - Image Tag: ${{ inputs.IMAGE_TAG }}
             - Actor: ${{ env.GITHUB_ACTOR }}
             - Job URL: ${{ env.JOB_URL }}
           color: good
         env:
-          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 
+          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}
 
       - name: Notify Slack of Failure
         if: failure()
         uses: voxmedia/github-action-slack-notify-build@v1
         with:
-          channel_id: ${{ inputs.SLACK_DEV_DEPLOY_CHANNEL_ID }}
-          message_id: ${{ steps.gh-deploy-dev.outputs.message_id }}
+          channel_id: ${{ inputs.SLACK_PROD_DEPLOY_CHANNEL_ID }}
+          message_id: ${{ steps.gh-deploy-prod.outputs.message_id }}
           status: |
-            Image DEV Deployment Failed
+            Image Production Deployment Failed
 
-            - Image Tag: ${{ env.TAG }}
+            - Image Tag: ${{ inputs.IMAGE_TAG }}
             - Actor: ${{ env.GITHUB_ACTOR }}
             - Job URL: ${{ env.JOB_URL }}
           color: danger
         env:
-          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 
+          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}
+
+
