NA-18020

diff --git a/.github/workflows/default_build_test.yaml b/.github/workflows/default_build_test.yaml
--- a/.github/workflows/default_build_test.yaml
+++ b/.github/workflows/default_build_test.yaml
@@ -20,10 +20,10 @@ on:
         type: string
         required: true
         description: 'Caching Elastic Container Repository of the service'
-      # MENTION_GROUP:
-      #    type: string
-      #   required: true
-      #   description: 'Group which will be notified for result of GHA workflow'     
+      MENTION_GROUP:
+         type: string
+        required: true
+        description: 'Group which will be notified for result of GHA workflow'     
     secrets:
       slack-bot-token:
         required: true
@@ -60,15 +60,16 @@ jobs:
           echo "GITHUB_ACTOR=${GITHUB_ACTOR}" >> $GITHUB_ENV
           echo "JOB_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
       
-      - name: Set output variables
-        id: set_output_variables
-        shell: bash
-        run: |
-          $attempt = [int]$env:GITHUB_RUN_ATTEMPT
-          $maxAttempts = [int]$env:maxAttempts
-          $nextAttempt = $attempt + 1
-          echo "::set-output name=nextAttempt::$nextAttempt"
-          echo "::set-output name=maxAttempts::$maxAttempts"
+      # - name: Set output variables
+      #   id: set_output_variables
+      #   run: |
+      #     echo "attempt=`echo ${GITHUB_RUN_ATTEMPT}`"
+      #     echo "maxAttempts=env.maxAttempts"
+      #     # $attempt = [int]$env:GITHUB_RUN_ATTEMPT
+      #     # $maxAttempts = [int]$env:maxAttempts
+      #     # $nextAttempt = $attempt + 1
+      #     # echo "::set-output name=nextAttempt::$nextAttempt"
+      #     # echo "::set-output name=maxAttempts::$maxAttempts"
 
       - name: Login to Docker Hub
         uses: docker/login-action@v2
@@ -169,37 +170,38 @@ jobs:
             - Image Tag: ${{ env.TAG }}
             - Actor: ${{ env.GITHUB_ACTOR }}
             - Job URL: ${{ env.JOB_URL }}
+            - Group: @${{ env.MENTION_GROUP}}
           color: danger
         env:
           SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 
 
-  rerun_workflow_job:
-    name: Rerun ${{ github.run_id }}
-    runs-on: small-runner
-    needs: default_build
-    if: failure() && ( needs.attempt_job.outputs.nextAttempt <= needs.attempt_job.outputs.maxAttempts )
-    env:
-      attempt: ${{ needs.attempt_job.outputs.nextAttempt }}
-    steps:
-      - name: "Trigger Attempt ${{ needs.attempt_job.outputs.nextAttempt }}"
-        shell: pwsh
-        env:
-          # GITHUB_TOKEN with actions: write will NOT work
-          # PAT Token must have workflow scope
-          gh-cli-token: ${{ secrets.GH_TOKEN_REPO_FULL }}
-        run: |
-          echo "Running gh auth login..."
-          $env:gh-cli-token | gh auth login --with-token
-          if(!$?) { exit 1 }
-          echo "Triggering rerun attempt $env:nextAttempt"
-          echo "
-          gh workflow run rerun-workflow.yml
-            --raw-field runId=$env:GITHUB_RUN_ID
-            --raw-field rerunFailedOnly=$env:rerunFailedOnly
-            --repo $env:GITHUB_REPOSITORY
-          "
-          gh workflow run rerun-workflow.yml `
-            --raw-field runId=$env:GITHUB_RUN_ID `
-            --raw-field rerunFailedOnly=$env:rerunFailedOnly `
-            --repo $env:GITHUB_REPOSITORY
-          if(!$?) { exit 1 }
+  # rerun_workflow_job:
+  #   name: Rerun ${{ github.run_id }}
+  #   runs-on: small-runner
+  #   needs: default_build
+  #   if: failure() && ( needs.attempt_job.outputs.nextAttempt <= needs.attempt_job.outputs.maxAttempts )
+  #   env:
+  #     attempt: ${{ needs.attempt_job.outputs.nextAttempt }}
+  #   steps:
+  #     - name: "Trigger Attempt ${{ needs.attempt_job.outputs.nextAttempt }}"
+  #       shell: pwsh
+  #       env:
+  #         # GITHUB_TOKEN with actions: write will NOT work
+  #         # PAT Token must have workflow scope
+  #         gh-cli-token: ${{ secrets.GH_TOKEN_REPO_FULL }}
+  #       run: |
+  #         echo "Running gh auth login..."
+  #         $env:gh-cli-token | gh auth login --with-token
+  #         if(!$?) { exit 1 }
+  #         echo "Triggering rerun attempt $env:nextAttempt"
+  #         echo "
+  #         gh workflow run rerun-workflow.yml
+  #           --raw-field runId=$env:GITHUB_RUN_ID
+  #           --raw-field rerunFailedOnly=$env:rerunFailedOnly
+  #           --repo $env:GITHUB_REPOSITORY
+  #         "
+  #         gh workflow run rerun-workflow.yml `
+  #           --raw-field runId=$env:GITHUB_RUN_ID `
+  #           --raw-field rerunFailedOnly=$env:rerunFailedOnly `
+  #           --repo $env:GITHUB_REPOSITORY
+  #         if(!$?) { exit 1 }
